from app.modules.identity.domain.enumerations import UserRole, UserRoles
from app.modules.identity.domain.policies import (
    PENDING_DOCUMENT_STATUS,
    can_change_document_status,
    can_create_document,
    can_delete_document,
    can_edit_document,
    can_manage_users,
    can_view_audit_logs,
    can_view_all_documents,
    can_view_document,
    has_any_role,
    has_role,
    is_admin,
    is_analyst,
    is_requester,
    normalize_role,
)

__all__ = [
    "UserRole",
    "UserRoles",
    "PENDING_DOCUMENT_STATUS",
    "normalize_role",
    "has_role",
    "has_any_role",
    "is_admin",
    "is_analyst",
    "is_requester",
    "can_manage_users",
    "can_view_audit_logs",
    "can_create_document",
    "can_view_all_documents",
    "can_view_document",
    "can_edit_document",
    "can_delete_document",
    "can_change_document_status",
]